/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Guests {
  fullName: string;
  id: number;
  isAttending: string;
  site: string;
  wishes: string;
  submittedAt: string;
}

export interface DB {
  guests: Guests;
}
